Merge branch 38-create-admin-view-for-registered-users to main
rakenduste-programmeerimine-2023/casa-catch pull request #40
Opened 2023-11-28 16:01 UTC by Rsilt

Closes #38

2023-11-28 16:38 UTC, janlever approved these changes
LGTM

2023-11-29 11:00 UTC, makuska requested changes

2023-11-29 11:00 UTC, MyrkurRoot commented on app/admin/page.tsx
> +export default async function Profile() {
Admin

2023-11-29 11:00 UTC, MyrkurRoot commented on app/adminpage
Delete empty file

2023-11-29 13:18 UTC, makuska approved these changes

2023-11-29 13:18 UTC, merged